-- +goose Up
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL CHECK (price > 0),
    user_id UUID NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_subscriptions_user_id_created_at ON subscriptions(user_id, created_at DESC);

CREATE INDEX idx_subscriptions_dates ON subscriptions(start_date, end_date);

-- +goose Down
DROP TABLE IF EXISTS subscriptions;
